# Generated by Django 2.2.7 on 2019-11-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuber', '0002_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
